generate_sequence_with_name.py
n_output_gate_instance
pNOutputGateInstance
AstNOutputGateInstance
zero_or_one_name_of_gate_instance ( output_terminal zero_or_more_comma_output_terminal , input_terminal )
